spring.application.name=task-system
server.port=8080

# Perfil activo por defecto
spring.profiles.active=dev

# JWT
app.jwt.secret=VGVjTWFuYWdlclNpc3RlbWFTZWd1cm8yMDI0Q2xhdmVTZWNyZXRhU3VwZXJMYXJnYQ==
app.jwt.expiration=86400000

# Logs
logging.level.com.taskSystem=DEBUG