spring.application.name=task-system
server.port=8080

# Perfil activo por defecto
spring.profiles.active=dev

# JWT
app.jwt.secret=clave-super-secreta-cambiar-en-produccion-minimo-256-bits-xxxxxxxxxxxxxxx
app.jwt.expiration=86400000

# Logs
logging.level.com.taskSystem=DEBUG