# ── Pega aquí tu connection string de MongoDB Atlas ──
# Lo encuentras en: Atlas → Connect → Drivers → Java
spring.data.mongodb.uri=mongodb+srv://bryan_db_user:062907062024@cluster0.boytdqb.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=tecmanager

# Ver queries de MongoDB en consola
logging.level.org.springframework.data.mongodb.core=DEBUG

de.flapdoodle.mongodb.embedded.version=7.0.2